### ISSUE TITLE
Wanna conntact me?

### ISSUE THREAD

**Issue by Eddyskingdom** [zaimoni/RSRevived#10]
i saw you have followed me so i was wondering if you wanna contact me?
i know this is not the best way to do it as it's sepost to be used for Issues but i had no other way to talk with you.
just message here if you wanna talk i'll get a email about it
@zaimoni

**Comment by zaimoni** [comment]
Not specifically.  One of my policies, is to GitHub-follow anyone who is not "robot-like" who forks one of my repositories, so I can be automatically notified when they star or fork a repository.

**Comment by Eddyskingdom** [comment]
alright either way i would love to work on this but i'm currently working on multiple project so time is short i might be able to help with spriting or something also it be good to build the community of RS back up again maybe you should start a discord or something
